{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-scraping-ai.fullname" . }}
  labels:
    {{- include "github-scraping-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecret.githubTokenKey }}: {{ .Values.config.github.token | quote }}
  {{ .Values.existingSecret.llmApiKeyKey }}: {{ .Values.config.llm.apiKey | quote }}
  {{ .Values.existingSecret.discordWebhookKey }}: {{ .Values.config.discord.webhookUrl | quote }}
{{- end }}
